ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "name" varchar(128) NOT NULL DEFAULT '';
ALTER TABLE "signup_requests" ADD COLUMN IF NOT EXISTS "name" varchar(128) NOT NULL DEFAULT '';

ALTER TABLE "users" ALTER COLUMN "name" DROP DEFAULT;
ALTER TABLE "signup_requests" ALTER COLUMN "name" DROP DEFAULT;
